### ISSUE TITLE
Epic:  Build a restaurant website with booking system.

### ISSUE THREAD

**Issue by jossansik** [jossansik/Portfolio-project4-restaurant-booking#1]
This status describes the larger scope of the project. It will be broken down into a number of smaller User stories which are achieved through tasks.

- [x] https://github.com/jossansik/Portfolio-project4-restaurant-booking/issues/11
- [x] https://github.com/jossansik/Portfolio-project4-restaurant-booking/issues/2
- [x] https://github.com/jossansik/Portfolio-project4-restaurant-booking/issues/3
- [x] https://github.com/jossansik/Portfolio-project4-restaurant-booking/issues/4
- [x] https://github.com/jossansik/Portfolio-project4-restaurant-booking/issues/6
- [x] https://github.com/jossansik/Portfolio-project4-restaurant-booking/issues/7
- [x] https://github.com/jossansik/Portfolio-project4-restaurant-booking/issues/8
- [x] https://github.com/jossansik/Portfolio-project4-restaurant-booking/issues/9
- [x] https://github.com/jossansik/Portfolio-project4-restaurant-booking/issues/10
- [x] https://github.com/jossansik/Portfolio-project4-restaurant-booking/issues/13
- [x] https://github.com/jossansik/Portfolio-project4-restaurant-booking/issues/14
- [x] https://github.com/jossansik/Portfolio-project4-restaurant-booking/issues/12
- [x] https://github.com/jossansik/Portfolio-project4-restaurant-booking/issues/16
